[FACE-1682] fix: [FE] 이더리움 테스트넷 Sepolia 지원
HAECHI-LABS/face-react-native-sample-dapp pull request #15
Opened 2023-12-01 07:54 UTC by imki123

# 티켓
- https://www.notion.so/haechilabs/FE-Sepolia-f86d4ab8bad64235817591b1968f388c
# 변경사항
- 이더리움 테스트넷을 변경합니다.
- Goerli -> Sepolia
- face-types 최신 버전이 v1.12.1 여서 ^1.12.2를 사용하도록 수정해뒀습니다. `sdk face-types 배포 후 rn샘플댑 배포되어야 합니다.`
- README 정리했습니다.

2023-12-01 08:16 UTC, EddieYS95 approved these changes

2023-12-05 01:51 UTC, borre-haechi commented on README.md
> +yarn
yarn으로 변경하는 건 어떻게 결정된 걸까요? 이 PR에서 다루기에는 너무 다른 맥락인 거 같은데 따로 PR로 진행하는 게 좋았을 거 같습니다.

2023-12-05 01:51 UTC, borre-haechi commented on README.md
> +yarn
저는 기존에 npm install을 쓰고 있었는데 npm 을 쓰면 안되는 이유가 있나요?

2023-12-05 01:52 UTC, borre-haechi requested changes
yarn으로 바뀌는 결정의 맥락이 궁금합니다.

애매하면 yarn바꾸는 건 다른 PR로 빼주세요.

2023-12-05 01:53 UTC, borre-haechi commented
@dot-haechi 기존에 npm과 yarn을 다 지원하는 것처럼 README.md에 적혀있었어요. yarn만 쓰기로 하는 건 도트랑 이야기된 걸까요?

2023-12-05 02:53 UTC, imki123 commented on README.md
> +yarn
네 보르 맥락 공유해드릴게요.
앱 배포하려고 빌드를 하는 도중에 실수로 pnpm instsll을 사용해서 빌드가 제대로 안되는 문제가 있었어요. 그래서 lock파일을 보니 npm, yarn을 둘다 사용하는 걸로 보였고 둘중에 yarn을 사용하는게 더 낫지 않을까 라는 생각에 yarn으로 바꿔뒀었어요.
이 프로젝트는 사실 npm을 쓰나 yarn을 쓰나 차이가 없어서 둘중에 하나로 고정하면 좋을 것 같아요.
저는 둘다 상관없어서 두분이 쓰기에 편하신걸로 정하면 될것 같아요! 
cc @dot-haechi

2023-12-05 02:53 UTC, imki123 commented on README.md
> +yarn
리드미는 우선 원복 해둘게요~

2023-12-06 02:01 UTC, dot-haechi commented
> @dot-haechi 기존에 npm과 yarn을 다 지원하는 것처럼 README.md에 적혀있었어요. yarn만 쓰기로 하는 건 도트랑 이야기된 걸까요?

네 우선 lock file 이 2개일 필요가 있을까, 싶은 생각에서였는데요, RN 공식 문서 등에서 yarn 을 주로 써서 yarn 으로 통일하는 게 좋지 않을까 싶었습니다.
그런데, 이게 sample dapp 인 걸 생각하면.. yarn, npm  유저 환경에 맞춰서 lock 파일이 생긴 걸까요? @imki123 cc

2023-12-06 02:59 UTC, borre-haechi commented
@dot-haechi 이야기 된 내용이면 좋습니다. cc @imki123 
갑작스럽게 들어가는 건가 싶었어요. 저는 README.md 를 읽고 주로 npm을 쓰고 있었어요. 그래서 npm이 문제가 있어서 없어지는 건가, 어떤 결정사항들이 있었나 궁금했습니다.

README.md 일 뿐이더라도 이런 결정에 대한 내용은 별도로 공유되고 머지되면 좋았을 거 같아요.
이 PR만 보기에는 후디가 작업하시다가 의논 없이 결정해서 머지하시는 걸로 오해했어요.

2023-12-06 03:00 UTC, borre-haechi approved these changes

2023-12-06 03:11 UTC, dot-haechi approved these changes

2023-12-06 03:12 UTC, merged